In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('data.csv', encoding='latin-1')

In [4]:
print(*df.columns, sep='\n')

iso3
country
hdicode
region
hdi_rank_2022
hdi_1990
hdi_1991
hdi_1992
hdi_1993
hdi_1994
hdi_1995
hdi_1996
hdi_1997
hdi_1998
hdi_1999
hdi_2000
hdi_2001
hdi_2002
hdi_2003
hdi_2004
hdi_2005
hdi_2006
hdi_2007
hdi_2008
hdi_2009
hdi_2010
hdi_2011
hdi_2012
hdi_2013
hdi_2014
hdi_2015
hdi_2016
hdi_2017
hdi_2018
hdi_2019
hdi_2020
hdi_2021
hdi_2022
le_1990
le_1991
le_1992
le_1993
le_1994
le_1995
le_1996
le_1997
le_1998
le_1999
le_2000
le_2001
le_2002
le_2003
le_2004
le_2005
le_2006
le_2007
le_2008
le_2009
le_2010
le_2011
le_2012
le_2013
le_2014
le_2015
le_2016
le_2017
le_2018
le_2019
le_2020
le_2021
le_2022
eys_1990
eys_1991
eys_1992
eys_1993
eys_1994
eys_1995
eys_1996
eys_1997
eys_1998
eys_1999
eys_2000
eys_2001
eys_2002
eys_2003
eys_2004
eys_2005
eys_2006
eys_2007
eys_2008
eys_2009
eys_2010
eys_2011
eys_2012
eys_2013
eys_2014
eys_2015
eys_2016
eys_2017
eys_2018
eys_2019
eys_2020
eys_2021
eys_2022
mys_1990
mys_1991
mys_1992
mys_1993
mys_1994
mys_1995
mys_1996
mys_1997
mys_1998
mys_1999
mys_2000
mys_2001
mys_2002
mys_2003
mys_2004
mys_2005
mys_2006
mys_2007
mys_2008
mys_2009
mys_2010
mys_2011
mys_2012
mys_2013
mys_2014
mys_2015
mys_2016
mys_2017
mys_2018
mys_2019
mys_2020
mys_2021
mys_2022
gnipc_1990
gnipc_1991
gnipc_1992
gnipc_1993
gnipc_1994
gnipc_1995
gnipc_1996
gnipc_1997
gnipc_1998
gnipc_1999
gnipc_2000
gnipc_2001
gnipc_2002
gnipc_2003
gnipc_2004
gnipc_2005
gnipc_2006
gnipc_2007
gnipc_2008
gnipc_2009
gnipc_2010
gnipc_2011
gnipc_2012
gnipc_2013
gnipc_2014
gnipc_2015
gnipc_2016
gnipc_2017
gnipc_2018
gnipc_2019
gnipc_2020
gnipc_2021
gnipc_2022
gdi_group_2022
gdi_1990
gdi_1991
gdi_1992
gdi_1993
gdi_1994
gdi_1995
gdi_1996
gdi_1997
gdi_1998
gdi_1999
gdi_2000
gdi_2001
gdi_2002
gdi_2003
gdi_2004
gdi_2005
gdi_2006
gdi_2007
gdi_2008
gdi_2009
gdi_2010
gdi_2011
gdi_2012
gdi_2013
gdi_2014
gdi_2015
gdi_2016
gdi_2017
gdi_2018
gdi_2019
gdi_2020
gdi_2021
gdi_2022
hdi_f_1990
hdi_f_1991
hdi_f_1992
hdi_f_1993
hdi_f_1994
hdi_f_1995
hdi_f_1996
hdi_f_1997
hdi_f_1998
hdi_f_1999
hdi_f_2000
hdi_f_2001
hdi_f_2002
hdi_f_2003
hdi_f_2004
hdi_f_2005
hdi_f_2006
hdi_f_2007
hdi_f_2008
hdi_f_2009
hdi_f_2010
hdi_f_2011
hdi_f_2012
hdi_f_2013
hdi_f_2014
hdi_f_2015
hdi_f_2016
hdi_f_2017
hdi_f_2018
hdi_f_2019
hdi_f_2020
hdi_f_2021
hdi_f_2022
le_f_1990
le_f_1991
le_f_1992
le_f_1993
le_f_1994
le_f_1995
le_f_1996
le_f_1997
le_f_1998
le_f_1999
le_f_2000
le_f_2001
le_f_2002
le_f_2003
le_f_2004
le_f_2005
le_f_2006
le_f_2007
le_f_2008
le_f_2009
le_f_2010
le_f_2011
le_f_2012
le_f_2013
le_f_2014
le_f_2015
le_f_2016
le_f_2017
le_f_2018
le_f_2019
le_f_2020
le_f_2021
le_f_2022
eys_f_1990
eys_f_1991
eys_f_1992
eys_f_1993
eys_f_1994
eys_f_1995
eys_f_1996
eys_f_1997
eys_f_1998
eys_f_1999
eys_f_2000
eys_f_2001
eys_f_2002
eys_f_2003
eys_f_2004
eys_f_2005
eys_f_2006
eys_f_2007
eys_f_2008
eys_f_2009
eys_f_2010
eys_f_2011
eys_f_2012
eys_f_2013
eys_f_2014
eys_f_2015
eys_f_2016
eys_f_2017
eys_f_2018
eys_f_2019
eys_f_2020
eys_f_2021
eys_f_2022
mys_f_1990
mys_f_1991
mys_f_1992
mys_f_1993
mys_f_1994
mys_f_1995
mys_f_1996
mys_f_1997
mys_f_1998
mys_f_1999
mys_f_2000
mys_f_2001
mys_f_2002
mys_f_2003
mys_f_2004
mys_f_2005
mys_f_2006
mys_f_2007
mys_f_2008
mys_f_2009
mys_f_2010
mys_f_2011
mys_f_2012
mys_f_2013
mys_f_2014
mys_f_2015
mys_f_2016
mys_f_2017
mys_f_2018
mys_f_2019
mys_f_2020
mys_f_2021
mys_f_2022
gni_pc_f_1990
gni_pc_f_1991
gni_pc_f_1992
gni_pc_f_1993
gni_pc_f_1994
gni_pc_f_1995
gni_pc_f_1996
gni_pc_f_1997
gni_pc_f_1998
gni_pc_f_1999
gni_pc_f_2000
gni_pc_f_2001
gni_pc_f_2002
gni_pc_f_2003
gni_pc_f_2004
gni_pc_f_2005
gni_pc_f_2006
gni_pc_f_2007
gni_pc_f_2008
gni_pc_f_2009
gni_pc_f_2010
gni_pc_f_2011
gni_pc_f_2012
gni_pc_f_2013
gni_pc_f_2014
gni_pc_f_2015
gni_pc_f_2016
gni_pc_f_2017
gni_pc_f_2018
gni_pc_f_2019
gni_pc_f_2020
gni_pc_f_2021
gni_pc_f_2022
hdi_m_1990
hdi_m_1991
hdi_m_1992
hdi_m_1993
hdi_m_1994
hdi_m_1995
hdi_m_1996
hdi_m_1997
hdi_m_1998
hdi_m_1999
hdi_m_2000
hdi_m_2001
hdi_m_2002
hdi_m_2003
hdi_m_2004
hdi_m_2005
hdi_m_2006
hdi_m_2007
hdi_m_2008
hdi_m_2009
hdi_m_2010
hdi_m_2011
hdi_m_2012
hdi_m_2013
hdi_m_2014
hdi_m_2015
hdi_m_2016
hdi_m_2017
hdi_m_2018
hdi_m_2019
hdi_m_2020
hdi_m_2021
hdi_m_2022
le_m_1990
le_m_1991
le_m_1992
le_m_1993
le_m_1994
le_m_1995
le_m_1996
le_m_1997
le_m_1998
le_m_1999
le_m_2000
le_m_2001
le_m_2002
le_m_2003
le_m_2004
le_m_2005
le_m_2006
le_m_2007
le_m_2008
le_m_2009
le_m_2010
le_m_2011
le_m_2012
le_m_2013
le_m_2014
le_m_2015
le_m_2016
le_m_2017
le_m_2018
le_m_2019
le_m_2020
le_m_2021
le_m_2022
eys_m_1990
eys_m_1991
eys_m_1992
eys_m_1993
eys_m_1994
eys_m_1995
eys_m_1996
eys_m_1997
eys_m_1998
eys_m_1999
eys_m_2000
eys_m_2001
eys_m_2002
eys_m_2003
eys_m_2004
eys_m_2005
eys_m_2006
eys_m_2007
eys_m_2008
eys_m_2009
eys_m_2010
eys_m_2011
eys_m_2012
eys_m_2013
eys_m_2014
eys_m_2015
eys_m_2016
eys_m_2017
eys_m_2018
eys_m_2019
eys_m_2020
eys_m_2021
eys_m_2022
mys_m_1990
mys_m_1991
mys_m_1992
mys_m_1993
mys_m_1994
mys_m_1995
mys_m_1996
mys_m_1997
mys_m_1998
mys_m_1999
mys_m_2000
mys_m_2001
mys_m_2002
mys_m_2003
mys_m_2004
mys_m_2005
mys_m_2006
mys_m_2007
mys_m_2008
mys_m_2009
mys_m_2010
mys_m_2011
mys_m_2012
mys_m_2013
mys_m_2014
mys_m_2015
mys_m_2016
mys_m_2017
mys_m_2018
mys_m_2019
mys_m_2020
mys_m_2021
mys_m_2022
gni_pc_m_1990
gni_pc_m_1991
gni_pc_m_1992
gni_pc_m_1993
gni_pc_m_1994
gni_pc_m_1995
gni_pc_m_1996
gni_pc_m_1997
gni_pc_m_1998
gni_pc_m_1999
gni_pc_m_2000
gni_pc_m_2001
gni_pc_m_2002
gni_pc_m_2003
gni_pc_m_2004
gni_pc_m_2005
gni_pc_m_2006
gni_pc_m_2007
gni_pc_m_2008
gni_pc_m_2009
gni_pc_m_2010
gni_pc_m_2011
gni_pc_m_2012
gni_pc_m_2013
gni_pc_m_2014
gni_pc_m_2015
gni_pc_m_2016
gni_pc_m_2017
gni_pc_m_2018
gni_pc_m_2019
gni_pc_m_2020
gni_pc_m_2021
gni_pc_m_2022
ihdi_2010
ihdi_2011
ihdi_2012
ihdi_2013
ihdi_2014
ihdi_2015
ihdi_2016
ihdi_2017
ihdi_2018
ihdi_2019
ihdi_2020
ihdi_2021
ihdi_2022
coef_ineq_2010
coef_ineq_2011
coef_ineq_2012
coef_ineq_2013
coef_ineq_2014
coef_ineq_2015
coef_ineq_2016
coef_ineq_2017
coef_ineq_2018
coef_ineq_2019
coef_ineq_2020
coef_ineq_2021
coef_ineq_2022
loss_2010
loss_2011
loss_2012
loss_2013
loss_2014
loss_2015
loss_2016
loss_2017
loss_2018
loss_2019
loss_2020
loss_2021
loss_2022
ineq_le_2010
ineq_le_2011
ineq_le_2012
ineq_le_2013
ineq_le_2014
ineq_le_2015
ineq_le_2016
ineq_le_2017
ineq_le_2018
ineq_le_2019
ineq_le_2020
ineq_le_2021
ineq_le_2022
ineq_edu_2010
ineq_edu_2011
ineq_edu_2012
ineq_edu_2013
ineq_edu_2014
ineq_edu_2015
ineq_edu_2016
ineq_edu_2017
ineq_edu_2018
ineq_edu_2019
ineq_edu_2020
ineq_edu_2021
ineq_edu_2022
ineq_inc_2010
ineq_inc_2011
ineq_inc_2012
ineq_inc_2013
ineq_inc_2014
ineq_inc_2015
ineq_inc_2016
ineq_inc_2017
ineq_inc_2018
ineq_inc_2019
ineq_inc_2020
ineq_inc_2021
ineq_inc_2022
gii_rank_2022
gii_1990
gii_1991
gii_1992
gii_1993
gii_1994
gii_1995
gii_1996
gii_1997
gii_1998
gii_1999
gii_2000
gii_2001
gii_2002
gii_2003
gii_2004
gii_2005
gii_2006
gii_2007
gii_2008
gii_2009
gii_2010
gii_2011
gii_2012
gii_2013
gii_2014
gii_2015
gii_2016
gii_2017
gii_2018
gii_2019
gii_2020
gii_2021
gii_2022
mmr_1990
mmr_1991
mmr_1992
mmr_1993
mmr_1994
mmr_1995
mmr_1996
mmr_1997
mmr_1998
mmr_1999
mmr_2000
mmr_2001
mmr_2002
mmr_2003
mmr_2004
mmr_2005
mmr_2006
mmr_2007
mmr_2008
mmr_2009
mmr_2010
mmr_2011
mmr_2012
mmr_2013
mmr_2014
mmr_2015
mmr_2016
mmr_2017
mmr_2018
mmr_2019
mmr_2020
mmr_2021
mmr_2022
abr_1990
abr_1991
abr_1992
abr_1993
abr_1994
abr_1995
abr_1996
abr_1997
abr_1998
abr_1999
abr_2000
abr_2001
abr_2002
abr_2003
abr_2004
abr_2005
abr_2006
abr_2007
abr_2008
abr_2009
abr_2010
abr_2011
abr_2012
abr_2013
abr_2014
abr_2015
abr_2016
abr_2017
abr_2018
abr_2019
abr_2020
abr_2021
abr_2022
se_f_1990
se_f_1991
se_f_1992
se_f_1993
se_f_1994
se_f_1995
se_f_1996
se_f_1997
se_f_1998
se_f_1999
se_f_2000
se_f_2001
se_f_2002
se_f_2003
se_f_2004
se_f_2005
se_f_2006
se_f_2007
se_f_2008
se_f_2009
se_f_2010
se_f_2011
se_f_2012
se_f_2013
se_f_2014
se_f_2015
se_f_2016
se_f_2017
se_f_2018
se_f_2019
se_f_2020
se_f_2021
se_f_2022
se_m_1990
se_m_1991
se_m_1992
se_m_1993
se_m_1994
se_m_1995
se_m_1996
se_m_1997
se_m_1998
se_m_1999
se_m_2000
se_m_2001
se_m_2002
se_m_2003
se_m_2004
se_m_2005
se_m_2006
se_m_2007
se_m_2008
se_m_2009
se_m_2010
se_m_2011
se_m_2012
se_m_2013
se_m_2014
se_m_2015
se_m_2016
se_m_2017
se_m_2018
se_m_2019
se_m_2020
se_m_2021
se_m_2022
pr_f_1990
pr_f_1991
pr_f_1992
pr_f_1993
pr_f_1994
pr_f_1995
pr_f_1996
pr_f_1997
pr_f_1998
pr_f_1999
pr_f_2000
pr_f_2001
pr_f_2002
pr_f_2003
pr_f_2004
pr_f_2005
pr_f_2006
pr_f_2007
pr_f_2008
pr_f_2009
pr_f_2010
pr_f_2011
pr_f_2012
pr_f_2013
pr_f_2014
pr_f_2015
pr_f_2016
pr_f_2017
pr_f_2018
pr_f_2019
pr_f_2020
pr_f_2021
pr_f_2022
pr_m_1990
pr_m_1991
pr_m_1992
pr_m_1993
pr_m_1994
pr_m_1995
pr_m_1996
pr_m_1997
pr_m_1998
pr_m_1999
pr_m_2000
pr_m_2001
pr_m_2002
pr_m_2003
pr_m_2004
pr_m_2005
pr_m_2006
pr_m_2007
pr_m_2008
pr_m_2009
pr_m_2010
pr_m_2011
pr_m_2012
pr_m_2013
pr_m_2014
pr_m_2015
pr_m_2016
pr_m_2017
pr_m_2018
pr_m_2019
pr_m_2020
pr_m_2021
pr_m_2022
lfpr_f_1990
lfpr_f_1991
lfpr_f_1992
lfpr_f_1993
lfpr_f_1994
lfpr_f_1995
lfpr_f_1996
lfpr_f_1997
lfpr_f_1998
lfpr_f_1999
lfpr_f_2000
lfpr_f_2001
lfpr_f_2002
lfpr_f_2003
lfpr_f_2004
lfpr_f_2005
lfpr_f_2006
lfpr_f_2007
lfpr_f_2008
lfpr_f_2009
lfpr_f_2010
lfpr_f_2011
lfpr_f_2012
lfpr_f_2013
lfpr_f_2014
lfpr_f_2015
lfpr_f_2016
lfpr_f_2017
lfpr_f_2018
lfpr_f_2019
lfpr_f_2020
lfpr_f_2021
lfpr_f_2022
lfpr_m_1990
lfpr_m_1991
lfpr_m_1992
lfpr_m_1993
lfpr_m_1994
lfpr_m_1995
lfpr_m_1996
lfpr_m_1997
lfpr_m_1998
lfpr_m_1999
lfpr_m_2000
lfpr_m_2001
lfpr_m_2002
lfpr_m_2003
lfpr_m_2004
lfpr_m_2005
lfpr_m_2006
lfpr_m_2007
lfpr_m_2008
lfpr_m_2009
lfpr_m_2010
lfpr_m_2011
lfpr_m_2012
lfpr_m_2013
lfpr_m_2014
lfpr_m_2015
lfpr_m_2016
lfpr_m_2017
lfpr_m_2018
lfpr_m_2019
lfpr_m_2020
lfpr_m_2021
lfpr_m_2022
rankdiff_hdi_phdi_2022
phdi_1990
phdi_1991
phdi_1992
phdi_1993
phdi_1994
phdi_1995
phdi_1996
phdi_1997
phdi_1998
phdi_1999
phdi_2000
phdi_2001
phdi_2002
phdi_2003
phdi_2004
phdi_2005
phdi_2006
phdi_2007
phdi_2008
phdi_2009
phdi_2010
phdi_2011
phdi_2012
phdi_2013
phdi_2014
phdi_2015
phdi_2016
phdi_2017
phdi_2018
phdi_2019
phdi_2020
phdi_2021
phdi_2022
diff_hdi_phdi_1990
diff_hdi_phdi_1991
diff_hdi_phdi_1992
diff_hdi_phdi_1993
diff_hdi_phdi_1994
diff_hdi_phdi_1995
diff_hdi_phdi_1996
diff_hdi_phdi_1997
diff_hdi_phdi_1998
diff_hdi_phdi_1999
diff_hdi_phdi_2000
diff_hdi_phdi_2001
diff_hdi_phdi_2002
diff_hdi_phdi_2003
diff_hdi_phdi_2004
diff_hdi_phdi_2005
diff_hdi_phdi_2006
diff_hdi_phdi_2007
diff_hdi_phdi_2008
diff_hdi_phdi_2009
diff_hdi_phdi_2010
diff_hdi_phdi_2011
diff_hdi_phdi_2012
diff_hdi_phdi_2013
diff_hdi_phdi_2014
diff_hdi_phdi_2015
diff_hdi_phdi_2016
diff_hdi_phdi_2017
diff_hdi_phdi_2018
diff_hdi_phdi_2019
diff_hdi_phdi_2020
diff_hdi_phdi_2021
diff_hdi_phdi_2022
co2_prod_1990
co2_prod_1991
co2_prod_1992
co2_prod_1993
co2_prod_1994
co2_prod_1995
co2_prod_1996
co2_prod_1997
co2_prod_1998
co2_prod_1999
co2_prod_2000
co2_prod_2001
co2_prod_2002
co2_prod_2003
co2_prod_2004
co2_prod_2005
co2_prod_2006
co2_prod_2007
co2_prod_2008
co2_prod_2009
co2_prod_2010
co2_prod_2011
co2_prod_2012
co2_prod_2013
co2_prod_2014
co2_prod_2015
co2_prod_2016
co2_prod_2017
co2_prod_2018
co2_prod_2019
co2_prod_2020
co2_prod_2021
co2_prod_2022
mf_1990
mf_1991
mf_1992
mf_1993
mf_1994
mf_1995
mf_1996
mf_1997
mf_1998
mf_1999
mf_2000
mf_2001
mf_2002
mf_2003
mf_2004
mf_2005
mf_2006
mf_2007
mf_2008
mf_2009
mf_2010
mf_2011
mf_2012
mf_2013
mf_2014
mf_2015
mf_2016
mf_2017
mf_2018
mf_2019
mf_2020
mf_2021
mf_2022
pop_total_1990
pop_total_1991
pop_total_1992
pop_total_1993
pop_total_1994
pop_total_1995
pop_total_1996
pop_total_1997
pop_total_1998
pop_total_1999
pop_total_2000
pop_total_2001
pop_total_2002
pop_total_2003
pop_total_2004
pop_total_2005
pop_total_2006
pop_total_2007
pop_total_2008
pop_total_2009
pop_total_2010
pop_total_2011
pop_total_2012
pop_total_2013
pop_total_2014
pop_total_2015
pop_total_2016
pop_total_2017
pop_total_2018
pop_total_2019
pop_total_2020
pop_total_2021
pop_total_2022

In [14]:
# key columns: country, region, hdicode, hdi_rank_2022
# year 1990 to 2022
df[['country', 'region', 'hdicode', 'hdi_rank_2022'] + ["hdi_" + str(year) for year in range(1990, 2023)]].head()

newdf = pd.DataFrame()

for year in range(1990, 2023):
    # new structure: country, region, hdicode, hdi_rank_2022, hdi, le, eys, gni, pop, year
    temp = df[['country', 'region', 'hdicode', 'hdi_rank_2022']].copy()
    temp['hdi'] = df[f'hdi_{year}']
    temp['le'] = df[f'le_{year}']
    temp['eys'] = df[f'eys_{year}']
    temp['gni'] = df[f'gnipc_{year}']
    temp['pop'] = df[f'pop_total_{year}']
    temp['year'] = year
    newdf = pd.concat([newdf, temp], ignore_index=True)

newdf.head()

,country,region,hdicode,hdi_rank_2022,hdi,le,eys,gni,pop,year
0,Afghanistan,SA,Low,182.0,0.284,45.967,2.936460,3115.670448,10.694796,1990
1,Albania,ECA,High,74.0,0.649,73.144,11.579340,4964.172443,3.295066,1990
2,Algeria,AS,High,93.0,0.593,67.416,9.797890,8592.763017,25.518074,1990
3,Andorra,NaN,Very High,35.0,NaN,78.406,9.567167,44541.254130,0.053569,1990
4,Angola,SSA,Medium,150.0,NaN,41.893,3.755630,5146.487368,11.828637,1990

In [15]:
newdf[newdf['country'] == 'India'].head()

,country,region,hdicode,hdi_rank_2022,hdi,le,eys,gni,pop,year
77,India,SA,Medium,134.0,0.434,58.652,8.016786,1795.941836,870.452165,1990
283,India,SA,Medium,134.0,0.437,59.055,8.038412,1773.797716,888.941756,1991
489,India,SA,Medium,134.0,0.442,59.452,8.060096,1832.898784,907.574049,1992
695,India,SA,Medium,134.0,0.446,59.815,8.081838,1882.700959,926.351296,1993
901,India,SA,Medium,134.0,0.452,60.216,8.103640,1970.353279,945.261958,1994

In [16]:
# save df as csv with name "final_data.csv"
newdf.to_csv("final_data.csv", index=False)